import {
  validateAdapterAgainstConfig,
  type Adapter,
  type AdapterInvocation,
  type AdapterResult,
} from '@pigmint/core';
import { manifest } from './manifest.js';
import { resolvePreset, type PresetName, type NameMapper } from './presets.js';

type Format = 'oklch' | 'hex';

const MODE_SELECTORS: Record<string, string> = {
  light: ':root',
  dark: '.dark',
  'light-high-contrast': '.light-high-contrast',
  'dark-high-contrast': '.dark-high-contrast',
};

function selectorForMode(mode: string, isDefault: boolean): string {
  if (isDefault) return ':root';
  return MODE_SELECTORS[mode] ?? `[data-mode="${mode}"]`;
}

function formatValue(value: Record<string, string>, format: Format): string {
  if (format === 'hex' && value.hex) return value.hex;
  if (value.oklch) return value.oklch;
  return value.hex ?? '#000';
}

interface SemanticTokenView {
  path: string;
  modes: Record<string, {
    value: { oklch?: string; hex?: string };
    source?: { ramp: string; position: number; nearestPrimitive?: string };
    contrast?: { wcag21?: number; apca?: number; againstBaseline?: number } | null;
    compliance?: { level?: string } | null;
  }>;
}

function walkSemanticTokens(
  node: Record<string, unknown>,
  prefix: string,
  out: SemanticTokenView[],
): void {
  const ext = node.$extensions as Record<string, unknown> | undefined;
  const pig = ext?.['com.pigmint'] as Record<string, unknown> | undefined;
  const modes = pig?.modes as SemanticTokenView['modes'] | undefined;
  if (modes && typeof node.$value === 'string') {
    out.push({ path: prefix, modes });
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (child && typeof child === 'object' && !Array.isArray(child)) {
      walkSemanticTokens(child as Record<string, unknown>, prefix ? `${prefix}.${key}` : key, out);
    }
  }
}

function collectSemanticTokens(color: Record<string, unknown>): SemanticTokenView[] {
  const out: SemanticTokenView[] = [];
  for (const [key, child] of Object.entries(color)) {
    if (key === 'primitive') continue;
    if (child && typeof child === 'object' && !Array.isArray(child)) {
      walkSemanticTokens(child as Record<string, unknown>, `color.${key}`, out);
    }
  }
  return out;
}

export function tailwindEmit(invocation: AdapterInvocation): AdapterResult {
  const warnings = validateAdapterAgainstConfig(
    manifest,
    invocation.adapterConfig,
    invocation.projectConfig,
  );

  const container = invocation.container;
  const preset = invocation.adapterConfig.preset as PresetName | undefined;
  const nameFor: NameMapper = resolvePreset(preset);

  const formats = invocation.adapterConfig.formats ?? ['oklch'];
  const format: Format = formats.includes('hex') && !formats.includes('oklch') ? 'hex' : 'oklch';
  // ADR-015: sRGB-only sinks (hex/hsl) reduce chroma; P3-aware sinks (oklch/p3) preserve it.
  const gamutDefault = format === 'hex' ? 'chroma-reduce' : 'chroma-preserve';

  const defaultMode = container.$extensions['com.pigmint'].defaultMode;
  const tokens = collectSemanticTokens(container.color as Record<string, unknown>);

  const modesInConfig = invocation.projectConfig.engine.modes;
  const sortedModes = [defaultMode, ...modesInConfig.filter((m) => m !== defaultMode)];

  const lines: string[] = [];
  lines.push('/* Generated by pigmint — do not edit by hand. */');
  lines.push(`/* DTCG source: ${invocation.projectConfig.output.dtcg} */`);
  lines.push(
    `/* Preset: ${preset ?? 'generic'}; format: ${format}; gamut: ${gamutDefault}; default mode: ${defaultMode} */`,
  );
  lines.push('');

  for (const mode of sortedModes) {
    const selector = selectorForMode(mode, mode === defaultMode);
    const modeLines: string[] = [];
    for (const t of tokens) {
      const entry = t.modes[mode];
      if (!entry) continue;
      const varName = nameFor(t.path);
      const value = formatValue(entry.value as Record<string, string>, format);
      const stepRef = entry.source?.nearestPrimitive ?? '—';
      const contrast = formatContrastComment(entry);
      modeLines.push(`  /* ${t.path} → ${stepRef}${contrast} */`);
      modeLines.push(`  ${varName}: ${value};`);
    }
    if (modeLines.length === 0) continue;
    lines.push(`${selector} {`);
    lines.push(...modeLines);
    lines.push('}');
    lines.push('');
  }

  const outputDir = invocation.adapterConfig.output.replace(/\/+$/, '');
  const filePath = `${outputDir}/tokens.css`;
  return {
    files: [{ path: filePath, content: lines.join('\n') }],
    warnings,
  };
}

function formatContrastComment(
  entry: SemanticTokenView['modes'][string],
): string {
  const c = entry.contrast;
  if (!c) return '';
  if (c.againstBaseline != null) return ` · baseline ${c.againstBaseline.toFixed(2)}:1`;
  const apcaLc = entry.compliance?.apcaLc;
  if (apcaLc) {
    return ` · Lc ${apcaLc.achieved.toFixed(1)} (min ${apcaLc.required.toFixed(0)})`;
  }
  const parts: string[] = [];
  if (c.wcag21 != null) parts.push(`wcag ${c.wcag21.toFixed(2)}:1`);
  if (c.apca != null) parts.push(`apca Lc ${c.apca.toFixed(1)}`);
  if (entry.compliance?.level) parts.push(entry.compliance.level);
  return parts.length ? ` · ${parts.join(', ')}` : '';
}

export const tailwindAdapter: Adapter = {
  manifest,
  emit: tailwindEmit,
};
