import {
  validateAdapterAgainstConfig,
  type Adapter,
  type AdapterInvocation,
  type AdapterResult,
} from '@pigmint/core';
import { manifest } from './manifest.js';
import { MUI_V6_PALETTE_BINDINGS, bindingsByTokenPath } from './palette-map.js';

type Format = 'hex' | 'oklch';

interface ModeEntryView {
  value: { hex?: string; oklch?: string };
}

interface TokenView {
  path: string;
  modes: Record<string, ModeEntryView>;
}

function walk(
  node: Record<string, unknown>,
  prefix: string,
  out: TokenView[],
): void {
  const ext = node.$extensions as Record<string, unknown> | undefined;
  const pig = ext?.['com.pigmint'] as Record<string, unknown> | undefined;
  const modes = pig?.modes as Record<string, ModeEntryView> | undefined;
  if (modes && typeof node.$value === 'string') {
    out.push({ path: prefix, modes });
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (child && typeof child === 'object' && !Array.isArray(child)) {
      walk(child as Record<string, unknown>, prefix ? `${prefix}.${key}` : key, out);
    }
  }
}

function collectTokens(color: Record<string, unknown>): TokenView[] {
  const out: TokenView[] = [];
  for (const [key, child] of Object.entries(color)) {
    if (key === 'primitive') continue;
    if (child && typeof child === 'object' && !Array.isArray(child)) {
      walk(child as Record<string, unknown>, `color.${key}`, out);
    }
  }
  return out;
}

function formatValue(view: ModeEntryView, format: Format): string | null {
  if (format === 'oklch' && view.value.oklch) return view.value.oklch;
  if (view.value.hex) return view.value.hex;
  return view.value.oklch ?? null;
}

function setAt(obj: Record<string, unknown>, path: string, value: string): void {
  const parts = path.split('.');
  let cursor = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    const key = parts[i]!;
    const next = cursor[key];
    if (next && typeof next === 'object' && !Array.isArray(next)) {
      cursor = next as Record<string, unknown>;
    } else {
      const fresh: Record<string, unknown> = {};
      cursor[key] = fresh;
      cursor = fresh;
    }
  }
  cursor[parts[parts.length - 1]!] = value;
}

interface BuildOutput {
  themeObject: {
    colorSchemes: Record<string, { palette: Record<string, unknown> }>;
  };
  receipts: {
    artifactVersion: 'mui-receipts@0.1';
    defaultMode: string;
    tokens: Array<{
      tokenPath: string;
      palettePaths: string[];
      modes: Record<string, string>;
    }>;
  };
  missingBindings: string[];
}

export function buildMuiOutput(
  invocation: AdapterInvocation,
  format: Format,
): BuildOutput {
  const container = invocation.container;
  const defaultMode = container.$extensions['com.pigmint'].defaultMode;
  const tokens = collectTokens(container.color as Record<string, unknown>);
  const bindings = bindingsByTokenPath();
  const modesInConfig = invocation.projectConfig.engine.modes;

  const themeObject: BuildOutput['themeObject'] = { colorSchemes: {} };
  const receiptsTokens: BuildOutput['receipts']['tokens'] = [];
  const bound = new Set<string>();

  for (const mode of modesInConfig) {
    themeObject.colorSchemes[mode] = { palette: {} };
  }

  for (const token of tokens) {
    const binding = bindings.get(token.path);
    if (!binding) continue;
    bound.add(token.path);

    const perMode: Record<string, string> = {};
    for (const mode of modesInConfig) {
      const entry = token.modes[mode];
      if (!entry) continue;
      const value = formatValue(entry, format);
      if (!value) continue;
      perMode[mode] = value;
      const palette = themeObject.colorSchemes[mode]!.palette;
      for (const palettePath of binding.palettePaths) {
        setAt(palette, palettePath, value);
      }
    }
    receiptsTokens.push({
      tokenPath: token.path,
      palettePaths: binding.palettePaths,
      modes: perMode,
    });
  }

  const missingBindings = MUI_V6_PALETTE_BINDINGS.map((b) => b.tokenPath).filter(
    (p) => !bound.has(p),
  );

  return {
    themeObject,
    receipts: {
      artifactVersion: 'mui-receipts@0.1',
      defaultMode,
      tokens: receiptsTokens,
    },
    missingBindings,
  };
}

function renderThemeFile(themeObject: BuildOutput['themeObject']): string {
  const body = JSON.stringify(themeObject, null, 2);
  return [
    '// Generated by pigmint — do not edit by hand.',
    "import { extendTheme } from '@mui/material/styles';",
    '',
    `export const pigmintThemeOptions = ${body} as const;`,
    '',
    'export const pigmintTheme = extendTheme(pigmintThemeOptions);',
    '',
  ].join('\n');
}

function renderReceiptsFile(receipts: BuildOutput['receipts']): string {
  return JSON.stringify(receipts, null, 2) + '\n';
}

export function muiEmit(invocation: AdapterInvocation): AdapterResult {
  const warnings = validateAdapterAgainstConfig(
    manifest,
    invocation.adapterConfig,
    invocation.projectConfig,
  );

  const formats = invocation.adapterConfig.formats ?? ['hex'];
  const format: Format = formats.includes('oklch') && !formats.includes('hex') ? 'oklch' : 'hex';

  const built = buildMuiOutput(invocation, format);

  const outputDir = invocation.adapterConfig.output.replace(/\/+$/, '');
  const themePath = `${outputDir}/theme.ts`;
  const receiptsPath = `${outputDir}/receipts.json`;

  if (built.missingBindings.length > 0) {
    warnings.push(
      `mui adapter: no DTCG tokens matched ${built.missingBindings.length} palette binding(s) — ${built.missingBindings.slice(0, 3).join(', ')}${built.missingBindings.length > 3 ? '…' : ''}`,
    );
  }

  return {
    files: [
      { path: themePath, content: renderThemeFile(built.themeObject) },
      { path: receiptsPath, content: renderReceiptsFile(built.receipts) },
    ],
    warnings,
  };
}

export const muiAdapter: Adapter = {
  manifest,
  emit: muiEmit,
};
